# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  serversideapp:
    image: serversideapp
    build:
      context: .
      dockerfile: ServerSideApp/ServerSideApp/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 62359:62359
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
